[package]
name = "unicount"
version = "0.1.3"
edition = "2021"
repository = "https://github.com/qtfkwk/unicount"
description = "Alphabetic counter supporting unicode"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive", "wrap_help"] }
clap-cargo = "0.15.2"
unescaper = "0.1.5"
unicount-lib = { version = "0.1.3", path = "../lib" }
